FROM cypress/base:18.6.0

USER root

RUN apt update && apt install -y sudo

RUN sudo npm install npm@latest cypress -g

RUN mkdir mybus_client

WORKDIR /mybus_client

COPY . ./

COPY ./package.json ./package-lock.json ./

RUN npm install

CMD ["yarn","start"]