FROM cypress/base:18.6.0

RUN mkdir mybus_client

WORKDIR /mybus_client

ENV PATH /mybus_client/node_modules/.bin:$PATH

COPY . ./

COPY ./package.json ./package-lock.json ./

RUN npm install

CMD ["yarn","start"]