FROM davidhailu0/dockercomposedebian:latest

RUN mkdir client

WORKDIR /client

ENV PATH /client/node_modules/.bin:$PATH

COPY ./package.json ./package-lock.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm","run","ci:e2e"]