export const places = [
    "Addis Ababa",
    "Adola/Kibremengist",
    "Agaro",
    "Alamata",
    "Arba Minch",
    "Assosa",
    "Bahir Dar",
    "Bedele",
    "Bichena",
    "Bonga",
    "Bule Hora",
    "Bure",
    "Chagni",
    "Dangla",
    "Debre Markos",
    "Debre Tabor",
    "Dembecha",
    "Dembidolo",
    "Dessie",
    "Dilla",
    "Dire Dawa",
    "Enjibara",
    "Finote Selam",
    "Gambela",
    "Gimbi",
    "Gondar",
    "Harar",
    "Hawassa",
    "Jijiga",
    "Jimma",
    "Kombolcha",
    "Kosober",
    "Kulbi Gebriel",
    "Mekane-Selam",
    "Mekele",
    "Mendi Nejo",
    "Merawi",
    "Mertole-Maryam",
    "Metu",
    "Mizan",
    "Motta",
    "Moyale",
    "Negele Borana",
    "Nekemte",
    "Robe",
    "Semera",
    "Wolayita Sodo",
    "Woldiya",
    "Yabelo"
]